name: Build Project

on:
  push:
    branches: [master]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [14.x]
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - run: npm ci
      - run: npm run build
      - name: Execute scripts
        working-directory: ./dist
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
          git init
          git add -A
          git commit -m "deploy"
          git push -f git@gitgub.com:FireRipper/FireRipper.github.io.git master:gh-pages
